### PR TITLE
Use Touchpad for move

### PR DESCRIPTION
**Pull request by omerfaruk**
Use touchpad axis for activate armswinger (top,bottom etc.)

### CODE REVIEW

**Comment by kjack9** [comment]
Much better, thanks!  Will review soon.

**Comment by omerfaruk** [comment]
i use 0.5f and -0.5f for buttons.I think someone who knows good math can make calculations on circle and make better version.In my version there some dead spot on touchpad.

 axisData.x < 0.5f && axisData.x > -0.5f

**Comment by kjack9** [comment]
After careful consideration, I'm going to close this PR without merging it.  While I appreciate the contribution, and it does work fine, I really feel like touchpad movement should be implemented separate from ArmSwinger.  I already half think that ArmSwing should be split into movement and player collisions scripts, and adding touchpad movement just adds crowding to an already crowded script.  Something like VRTK or NewtonVR is a much better place for the additional functionality.

Thanks again for contributing.

**Comment by omerfaruk** [comment]
It just activate armswinger with touchpad button.I think this script need this.Because in our game we use grip button for reload and trigger for shoot.We have to use axis for walk.

**Pull request closed without merging**
